### PR TITLE
Bugfixing and enhancments from upstream

### PR DESCRIPTION
**Pull request by Antash**
Hi Team, you may want to update to latest from upstream: a lot of useful changes appear.
1. GC sparsed data fixed
2. Strava new auth
3. Duplicated functionality removed (SourceFile)
4. Dropbox bugs fixed

### CODE REVIEW

**Comment by canssens** [comment]
Hello @Antash thank you for your PR, we will try to keep synchronization to your repo.
If we do improvments , we will try to propose them to you.

On our side, we are going to tune the display to our need, and we are going to remove RabbitMQ and Mongo to use managed service from AWS.

**Comment by Antash** [comment]
@canssens how come you have write permissions to exercisync repo? O_o

**Comment by canssens** [comment]
hello @Antash i am not sure what i did. I just wanted to merge into our fork (hub-decathlon) and not in your repository;
I don't understand how it is possible and how i did it.
Do you know what i did wrong?

Maybe you could reset your master branch to your last commit to correct this problem.

**Comment by Antash** [comment]
Hi @canssens I guess you just merged your master to upstream-master and pushed instead of creating PR. Looks like my repo settings consider contributors as valid commiters. Need to check that. Do not worry about it, I will just reset master's head.

**Comment by canssens** [comment]
Ok , i am surprised about that, i thinked i would be blocked by a need of PR.
We are going to use now a specific branch for our specific need.

When i merged this morning, i did it by the github webpage and it doesn't show that i going to push in the upstream
image

On the local side, we didn't configure the upstream to your repo.

**Comment by Antash** [comment]
Agree this is very strange.

**Pull request merged**
